### PR TITLE
Swap prebuild setupdesign library with the OSS version.

### LINKED ISSUE #191: Couldn't launch 'test dpc' app built myself
BuildInfo
os : Ubuntu 22.04
last commit : d830cac740ee22719a422024cb975adac160d960

Hi
I builded test dpc app myself and try to launch
But I faced below fatal exception

```
2023-11-25 22:54:03.689  6437-6437  AndroidRuntime          com.afwsamples.testdpc               E  FATAL EXCEPTION: main
                                                                                                    Process: com.afwsamples.testdpc, PID: 6437
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afwsamples.testdpc/com.afwsamples.testdpc.SetupManagementActivity}: android.view.InflateException: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Error inflating class com.google.android.setupdesign.GlifLayout
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Error inflating class com.google.android.setupdesign.GlifLayout
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #17 in com.afwsamples.testdpc:layout/setup_management_fragment: Error inflating class com.google.android.setupdesign.GlifLayout
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:866)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:667)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.afwsamples.testdpc.SetupManagementFragment.onCreateView(SetupManagementFragment.java:106)
                                                                                                    	at android.app.Fragment.performCreateView(Fragment.java:2510)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
                                                                                                    	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
                                                                                                    	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
                                                                                                    	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
                                                                                                    	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
                                                                                                    	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8604)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-11-25 22:54:03.691  6437-6437  AndroidRuntime          com.afwsamples.testdpc               E  	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #24 in com.afwsamples.testdpc:layout/sud_glif_template: Binary XML file line #57 in com.afwsamples.testdpc:layout/sud_glif_header: Error inflating class com.google.android.setupdesign.view.RichTextView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #57 in com.afwsamples.testdpc:layout/sud_glif_header: Error inflating class com.google.android.setupdesign.view.RichTextView
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.google.android.setupdesign.view.RichTextView
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:536)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:827)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
                                                                                                    	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1275)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
                                                                                                    	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1275)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.google.android.setupcompat.internal.TemplateLayout.inflateTemplate(TemplateLayout.java:177)
                                                                                                    	at com.google.android.setupdesign.GlifLayout.onInflateTemplate(GlifLayout.java:286)
                                                                                                    	at com.google.android.setupcompat.internal.TemplateLayout.inflateTemplate(TemplateLayout.java:141)
                                                                                                    	at com.google.android.setupcompat.internal.TemplateLayout.init(TemplateLayout.java:83)
                                                                                                    	at com.google.android.setupcompat.internal.TemplateLayout.<init>(TemplateLayout.java:62)
                                                                                                    	at com.google.android.setupcompat.PartnerCustomizationLayout.<init>(PartnerCustomizationLayout.java:101)
                                                                                                    	at com.google.android.setupdesign.GlifLayout.<init>(GlifLayout.java:98)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:866)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:667)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.afwsamples.testdpc.SetupManagementFragment.onCreateView(SetupManagementFragment.java:106)
                                                                                                    	at android.app.Fragment.performCreateView(Fragment.java:2510)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
                                                                                                    	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
                                                                                                    	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
                                                                                                    	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
                                                                                                    	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
2023-11-25 22:54:03.692  6437-6437  AndroidRuntime          com.afwsamples.testdpc               E  	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
                                                                                                    	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8604)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.setupdesign.view.RichTextView" on path: DexPathList[[zip file "/data/app/~~mJGSEYHH17cZJgAn8FSnkg==/com.afwsamples.testdpc-AgMTG8wUTxTa611jK_JDiw==/base.apk"],nativeLibraryDirectories=[/data/app/~~mJGSEYHH17cZJgAn8FSnkg==/com.afwsamples.testdpc-AgMTG8wUTxTa611jK_JDiw==/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 59 more
```

It seems aar files in lib folder something wrong.
Could you check?

### PR DESCRIPTION
**Pull request by pfmaggi**
Based on top of @ahumesky's [PR] this fixes #191:

- Remove prebuild `setupdesign` and `setupcompat` libraries
- Add Bazel's build for `setupdesign` and `setupcompat`
- Update `WORKSPACE` to patch `setupdesign` library to support Java 8
- Remove `appComponentFactory` in `AndroidManifest.xml`
- Fix in SUW layouts (`sucUsePartnerResource`)

[PR]: https://github.com/pfmaggi/android-testdpc/pull/1

### CODE REVIEW

**Review by jscott1989 — APPROVED** [review]

**Comment by SM2A** [comment]
Hi
What was wrong with `android_local_test`?
Why while `android_local_test` are commented `robolectric` library is still there?
@pfmaggi @jscott1989

**Comment by pfmaggi** [comment]
I had some issues with the `android_local_test` rules and I disabled it for the moment.

The plan is to enable them again once they are fixed.

**Comment by SM2A** [comment]
Is there anything I can help with?

**Comment by pfmaggi** [comment]
I filed #207 to track this. It would be nice to have a working testing setup with Bazel but I don't have time to work on this at the moment.

**Pull request merged**
